### PR TITLE
(post) pco check-ins and dymo

### PR DESCRIPTION
**Pull request by rmosolgo**
I just had to talk to _somebody_ about it!

This also adds tables:

image

### CODE REVIEW

**Comment by rmosolgo** [comment]
Here's that table on a mini-view

image

**Comment by skylarsch** [comment]
+1

**Comment by bensie** [comment]
:+1:

**Comment by jakegavin** [comment]
:+1: Nice!

**Comment by rmosolgo** [comment]
@skylarsch if you dig it, could you merge it? I don't have permission

**Pull request merged**
